<?php
/**
 * Blog Post Detail Template
 * Omniwallet CMS
 */
?>

<!-- Post Header -->
<article class="blog-post">
    <header class="post-header <?= $post['hero_image'] ? 'has-hero-image' : '' ?>"
            <?php if ($post['hero_image']): ?>
            style="background-image: url('<?= htmlspecialchars($post['hero_image']) ?>');"
            <?php endif; ?>>
        <div class="post-header-overlay"></div>
        <div class="container">
            <div class="post-header-content">
                <?php if ($post['category_name'] ?? false): ?>
                    <a href="/observatorio-saas?categoria=<?= htmlspecialchars($post['category_slug']) ?>" class="post-category">
                        <?= htmlspecialchars($post['category_name']) ?>
                    </a>
                <?php endif; ?>

                <div class="post-title-pill">
                    <h1><?= htmlspecialchars($post['title']) ?></h1>
                    <?php if (!empty($post['subtitle'])): ?>
                        <p class="post-subtitle"><?= htmlspecialchars($post['subtitle']) ?></p>
                    <?php endif; ?>
                </div>

                <div class="post-meta">
                    <span>
                        <i class="far fa-calendar"></i>
                        <?= date('d M Y', strtotime($post['published_at'] ?? $post['created_at'])) ?>
                    </span>
                    <?php if ($post['author_name'] ?? false): ?>
                        <span>
                            <i class="far fa-user"></i>
                            <?= htmlspecialchars($post['author_name']) ?>
                        </span>
                    <?php endif; ?>
                    <?php if ($post['read_time'] ?? false): ?>
                        <span>
                            <i class="far fa-clock"></i>
                            <?= $post['read_time'] ?> min de lectura
                        </span>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </header>

    <div class="post-body">
        <div class="container">
            <div class="post-layout">
                <!-- Main Content -->
                <div class="post-content">
                    <?php if ($post['excerpt']): ?>
                        <p class="post-excerpt"><?= htmlspecialchars($post['excerpt']) ?></p>
                    <?php endif; ?>

                    <div class="post-text">
                        <?= $post['content'] ?>
                    </div>

                    <?php if (!empty($post['tags'])): ?>
                        <div class="post-tags">
                            <span>Tags:</span>
                            <?php foreach (explode(',', $post['tags']) as $tag): ?>
                                <a href="/observatorio-saas?tag=<?= urlencode(trim($tag)) ?>" class="tag">
                                    <?= htmlspecialchars(trim($tag)) ?>
                                </a>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>

                <!-- Sidebar -->
                <aside class="post-sidebar">
                    <!-- Table of Contents (Accordion) -->
                    <div class="sidebar-widget toc-widget" id="toc-widget">
                        <button class="toc-toggle" id="toc-toggle" aria-expanded="false">
                            <span><i class="fas fa-list-ul"></i> Contenido</span>
                            <i class="fas fa-chevron-down toc-arrow"></i>
                        </button>
                        <nav id="table-of-contents" class="toc-content collapsed">
                            <!-- Generated by JavaScript -->
                        </nav>
                    </div>

                    <!-- Categories -->
                    <?php if (!empty($categories)): ?>
                        <div class="sidebar-widget categories-widget">
                            <h4>Categorías</h4>
                            <ul class="categories-list">
                                <?php foreach ($categories as $category): ?>
                                    <li>
                                        <a href="/observatorio-saas?categoria=<?= htmlspecialchars($category['slug']) ?>">
                                            <?= htmlspecialchars($category['name']) ?>
                                            <span class="post-count"><?= $category['post_count'] ?></span>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                </aside>
            </div>
        </div>
    </div>

    <!-- LLM Q&A Section -->
    <?php
    if (!empty($post['enable_llm_qa']) && !empty($post['llm_qa_content'])) {
        $llmQaItems = json_decode($post['llm_qa_content'], true) ?: [];
        $llmQaEntityType = 'post';
        $llmQaEntityId = $post['id'];
        include TEMPLATES_PATH . '/frontend/partials/llm-qa-section.php';
    }
    ?>

    <!-- Related Posts -->
    <?php if (!empty($relatedPosts)): ?>
        <section class="related-posts section">
            <div class="container">
                <h2>Artículos relacionados</h2>
                <div class="posts-grid">
                    <?php foreach ($relatedPosts as $related): ?>
                        <article class="post-card">
                            <?php if ($related['thumbnail']): ?>
                                <a href="/observatorio-saas/<?= htmlspecialchars($related['slug']) ?>" class="post-image">
                                    <img src="<?= htmlspecialchars($related['thumbnail']) ?>"
                                         alt="<?= htmlspecialchars($related['title']) ?>">
                                </a>
                            <?php endif; ?>
                            <div class="post-content">
                                <h3>
                                    <a href="/observatorio-saas/<?= htmlspecialchars($related['slug']) ?>">
                                        <?= htmlspecialchars($related['title']) ?>
                                    </a>
                                </h3>
                                <div class="post-meta">
                                    <span>
                                        <i class="far fa-calendar"></i>
                                        <?= date('d M Y', strtotime($related['published_at'] ?? $related['created_at'])) ?>
                                    </span>
                                </div>
                            </div>
                        </article>
                    <?php endforeach; ?>
                </div>
            </div>
        </section>
    <?php endif; ?>
</article>

<style>
/* Post Header */
.post-header {
    position: relative;
    padding: calc(var(--spacing-3xl) + var(--header-height)) 0 var(--spacing-3xl);
    background-color: var(--color-gray-900);
    text-align: center;
    min-height: 400px;
    display: flex;
    align-items: center;
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
}

.post-header.has-hero-image {
    min-height: 500px;
}

.post-header-overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: linear-gradient(
        to bottom,
        rgba(0, 0, 0, 0.4) 0%,
        rgba(0, 0, 0, 0.6) 50%,
        rgba(0, 0, 0, 0.7) 100%
    );
    z-index: 1;
}

.post-header .container {
    position: relative;
    z-index: 2;
}

.post-header-content {
    max-width: 900px;
    margin: 0 auto;
}

.post-header .post-category {
    display: inline-block;
    background-color: var(--color-primary);
    color: var(--color-white);
    padding: var(--spacing-xs) var(--spacing-md);
    border-radius: var(--radius-full);
    font-size: var(--font-size-sm);
    font-weight: 600;
    margin-bottom: var(--spacing-lg);
    text-decoration: none;
    transition: transform 0.2s ease, background-color 0.2s ease;
}

.post-header .post-category:hover {
    background-color: var(--color-primary-dark, var(--color-primary));
    transform: translateY(-2px);
}

/* Title Pill - White background for readability */
.post-title-pill {
    background: rgba(255, 255, 255, 0.95);
    padding: var(--spacing-xl) var(--spacing-2xl);
    border-radius: var(--radius-xl);
    margin-bottom: var(--spacing-xl);
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
    backdrop-filter: blur(10px);
}

.post-title-pill h1 {
    font-size: var(--font-size-4xl);
    margin: 0;
    line-height: 1.2;
    color: var(--color-gray-900);
}

.post-subtitle {
    font-size: var(--font-size-lg);
    color: var(--color-gray-600);
    margin: var(--spacing-sm) 0 0 0;
    line-height: 1.4;
    font-weight: 400;
}

.post-header .post-meta {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    gap: var(--spacing-lg);
    color: rgba(255, 255, 255, 0.9);
    font-size: var(--font-size-sm);
}

.post-header .post-meta span {
    background: rgba(255, 255, 255, 0.15);
    padding: var(--spacing-xs) var(--spacing-md);
    border-radius: var(--radius-full);
    backdrop-filter: blur(5px);
}

.post-header .post-meta i {
    margin-right: var(--spacing-xs);
}

/* Mobile adjustments for header */
@media (max-width: 768px) {
    .post-header {
        min-height: 350px;
        padding: calc(var(--spacing-2xl) + var(--header-height)) var(--spacing-md) var(--spacing-2xl);
    }

    .post-header.has-hero-image {
        min-height: 400px;
    }

    .post-title-pill {
        padding: var(--spacing-lg) var(--spacing-xl);
    }

    .post-title-pill h1 {
        font-size: var(--font-size-2xl);
    }

    .post-subtitle {
        font-size: var(--font-size-base);
    }

    .post-header .post-meta {
        gap: var(--spacing-sm);
    }

    .post-header .post-meta span {
        padding: var(--spacing-xs) var(--spacing-sm);
        font-size: var(--font-size-xs);
    }
}

/* Post Body - spacing from header */
.post-body {
    padding-top: 40px;
}

/* Post Layout */
.post-layout {
    display: grid;
    grid-template-columns: 1fr 300px;
    gap: var(--spacing-2xl);
}

/* Post Content */
.post-content {
    max-width: 100%;
}

.post-excerpt {
    font-size: var(--font-size-xl);
    color: var(--color-gray-600);
    line-height: 1.6;
    margin-bottom: var(--spacing-xl);
    padding-bottom: var(--spacing-xl);
    border-bottom: 1px solid var(--color-gray-200);
}

.post-text {
    font-size: var(--font-size-lg);
    line-height: 1.8;
    color: var(--color-gray-700);
}

.post-text h2 {
    font-size: var(--font-size-2xl);
    margin-top: var(--spacing-2xl);
    margin-bottom: var(--spacing-md);
}

.post-text h3 {
    font-size: var(--font-size-xl);
    margin-top: var(--spacing-xl);
    margin-bottom: var(--spacing-md);
}

.post-text p {
    margin-bottom: var(--spacing-md);
}

.post-text ul,
.post-text ol {
    margin-bottom: var(--spacing-md);
    padding-left: var(--spacing-xl);
}

.post-text li {
    margin-bottom: var(--spacing-sm);
}

.post-text img {
    max-width: 100%;
    height: auto;
    border-radius: var(--radius-lg);
    margin: var(--spacing-lg) 0;
}

.post-text blockquote {
    border-left: 4px solid var(--color-primary);
    padding-left: var(--spacing-lg);
    margin: var(--spacing-xl) 0;
    font-style: italic;
    color: var(--color-gray-600);
}

.post-text code {
    background-color: var(--color-gray-100);
    padding: 2px 6px;
    border-radius: var(--radius-sm);
    font-family: monospace;
}

.post-text pre {
    background-color: var(--color-gray-900);
    color: var(--color-gray-100);
    padding: var(--spacing-lg);
    border-radius: var(--radius-lg);
    overflow-x: auto;
    margin: var(--spacing-lg) 0;
}

.post-text pre code {
    background: none;
    padding: 0;
}

/* Tags */
.post-tags {
    display: flex;
    flex-wrap: wrap;
    gap: var(--spacing-sm);
    align-items: center;
    margin-top: var(--spacing-2xl);
    padding-top: var(--spacing-xl);
    border-top: 1px solid var(--color-gray-200);
}

.post-tags > span {
    color: var(--color-gray-500);
    font-weight: 600;
}

.tag {
    background-color: var(--color-gray-100);
    color: var(--color-gray-700);
    padding: var(--spacing-xs) var(--spacing-md);
    border-radius: var(--radius-full);
    font-size: var(--font-size-sm);
    transition: all var(--transition);
}

.tag:hover {
    background-color: var(--color-primary);
    color: var(--color-white);
}

/* Sidebar */
.post-sidebar {
    position: -webkit-sticky !important;
    position: sticky !important;
    top: 100px !important;
    height: fit-content !important;
    align-self: start !important;
    max-height: calc(100vh - 120px);
    overflow-y: auto;
}

.sidebar-widget {
    background-color: var(--color-white);
    border-radius: var(--radius-lg);
    padding: var(--spacing-lg);
    margin-bottom: var(--spacing-lg);
    box-shadow: var(--shadow-sm);
}

.sidebar-widget h4 {
    font-size: var(--font-size-base);
    margin-bottom: var(--spacing-md);
    padding-bottom: var(--spacing-sm);
    border-bottom: 2px solid var(--color-primary);
}

/* TOC Widget - Accordion */
.toc-widget {
    padding: 0;
    overflow: hidden;
}

.toc-toggle {
    width: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: var(--spacing-md) var(--spacing-lg);
    background: none;
    border: none;
    cursor: pointer;
    font-size: var(--font-size-sm);
    font-weight: 600;
    color: var(--color-gray-700);
    transition: all var(--transition);
}

.toc-toggle:hover {
    background-color: var(--color-gray-50);
}

.toc-toggle span {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
}

.toc-arrow {
    transition: transform 0.3s ease;
}

.toc-toggle[aria-expanded="true"] .toc-arrow {
    transform: rotate(180deg);
}

.toc-content {
    font-size: var(--font-size-sm);
    padding: 0 var(--spacing-lg) var(--spacing-lg);
    max-height: 400px;
    overflow: hidden;
    transition: max-height 0.3s ease, padding 0.3s ease;
}

.toc-content.collapsed {
    max-height: 0;
    padding-bottom: 0;
}

#table-of-contents a {
    display: block;
    padding: var(--spacing-xs) 0;
    color: var(--color-gray-600);
    border-left: 2px solid transparent;
    padding-left: var(--spacing-sm);
    transition: all var(--transition);
}

#table-of-contents a:hover,
#table-of-contents a.active {
    color: var(--color-primary);
    border-left-color: var(--color-primary);
}

#table-of-contents a.level-3 {
    padding-left: var(--spacing-lg);
}

/* Categories Widget */
.categories-widget h4 {
    margin-bottom: var(--spacing-md);
    padding-bottom: var(--spacing-sm);
    border-bottom: 2px solid var(--color-primary);
}

.categories-list {
    list-style: none;
    padding: 0;
    margin: 0;
}

.categories-list li {
    border-bottom: 1px solid var(--color-gray-100);
}

.categories-list li:last-child {
    border-bottom: none;
}

.categories-list a {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: var(--spacing-sm) 0;
    color: var(--color-gray-700);
    transition: all var(--transition);
}

.categories-list a:hover {
    color: var(--color-primary);
    padding-left: var(--spacing-xs);
}

.categories-list .post-count {
    background-color: var(--color-gray-100);
    color: var(--color-gray-600);
    font-size: var(--font-size-xs);
    padding: 2px 8px;
    border-radius: var(--radius-full);
    font-weight: 600;
}

.categories-list a:hover .post-count {
    background-color: var(--color-primary);
    color: var(--color-white);
}

/* Related Posts */
.related-posts {
    background-color: var(--color-gray-50);
}

.related-posts h2 {
    text-align: center;
    margin-bottom: var(--spacing-xl);
}

.related-posts .posts-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: var(--spacing-lg);
}

.related-posts .post-card {
    background-color: var(--color-white);
    border-radius: var(--radius-lg);
    overflow: hidden;
    box-shadow: var(--shadow-sm);
    transition: all var(--transition);
}

.related-posts .post-card:hover {
    box-shadow: var(--shadow-md);
    transform: translateY(-2px);
}

.related-posts .post-image {
    display: block;
    aspect-ratio: 16/9;
    overflow: hidden;
}

.related-posts .post-image img {
    width: 100%;
    height: 100%;
    object-fit: cover;
}

.related-posts .post-content {
    padding: var(--spacing-lg);
}

.related-posts .post-content h3 {
    font-size: var(--font-size-base);
    margin-bottom: var(--spacing-sm);
}

.related-posts .post-content h3 a {
    color: var(--color-dark);
}

.related-posts .post-meta {
    font-size: var(--font-size-sm);
    color: var(--color-gray-500);
}

@media (max-width: 1024px) {
    .post-layout {
        grid-template-columns: 1fr;
    }

    .post-sidebar {
        position: static;
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: var(--spacing-lg);
    }

    .toc-widget {
        display: none;
    }
}

@media (max-width: 768px) {
    .post-header h1 {
        font-size: var(--font-size-2xl);
    }

    .post-header .post-meta {
        flex-direction: column;
        gap: var(--spacing-sm);
    }

    .post-sidebar {
        grid-template-columns: 1fr;
    }

    .related-posts .posts-grid {
        grid-template-columns: 1fr;
    }
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Generate Table of Contents
    const postText = document.querySelector('.post-text');
    const toc = document.getElementById('table-of-contents');
    const tocWidget = document.getElementById('toc-widget');
    const tocToggle = document.getElementById('toc-toggle');
    const headings = postText.querySelectorAll('h2, h3');

    if (headings.length > 0 && toc) {
        headings.forEach((heading, index) => {
            const id = 'heading-' + index;
            heading.id = id;

            const link = document.createElement('a');
            link.href = '#' + id;
            link.textContent = heading.textContent;
            link.className = 'level-' + heading.tagName.toLowerCase().replace('h', '');
            toc.appendChild(link);
        });

        // TOC Accordion toggle
        tocToggle.addEventListener('click', function() {
            const isExpanded = this.getAttribute('aria-expanded') === 'true';
            this.setAttribute('aria-expanded', !isExpanded);
            toc.classList.toggle('collapsed');
        });

        // Highlight active TOC item on scroll
        const tocLinks = toc.querySelectorAll('a');
        window.addEventListener('scroll', function() {
            let current = '';
            headings.forEach(heading => {
                const rect = heading.getBoundingClientRect();
                if (rect.top <= 100) {
                    current = heading.id;
                }
            });

            tocLinks.forEach(link => {
                link.classList.remove('active');
                if (link.getAttribute('href') === '#' + current) {
                    link.classList.add('active');
                }
            });
        });
    } else if (tocWidget) {
        tocWidget.style.display = 'none';
    }
});
</script>
