<?php
/**
 * SEO Controller
 * Manages SEO metadata, sitemap, and robots.txt
 * Omniwallet CMS Admin
 */

namespace App\Controllers\Admin;

use App\Core\Controller;
use App\Models\SEOMetadata;
use App\Models\Setting;
use App\Services\SEOGeneratorService;
use App\Services\SEOService;

class SEOController extends Controller
{
    private SEOMetadata $seoModel;
    private SEOGeneratorService $seoGenerator;
    private Setting $settings;

    public function __construct()
    {
        parent::__construct();
        $this->requireAuth();
        $this->seoModel = new SEOMetadata();
        $this->seoGenerator = new SEOGeneratorService();
        $this->settings = new Setting();
    }

    /**
     * SEO Dashboard - Overview and statistics
     */
    public function index(): void
    {
        $stats = $this->seoModel->getStats();

        // Calculate totals
        $totalEntities = 0;
        $totalWithSeo = 0;
        $totalAutoGenerated = 0;

        foreach ($stats as $stat) {
            $totalEntities += $stat['total'];
            $totalWithSeo += $stat['with_seo'];
            $totalAutoGenerated += $stat['auto_generated'];
        }

        $overallPercentage = $totalEntities > 0 ? round(($totalWithSeo / $totalEntities) * 100) : 0;

        // Get recent audit log
        $recentActivity = $this->seoGenerator->getAuditLog(10);

        $this->renderAdmin('seo/index', [
            'title' => 'SEO Dashboard',
            'stats' => $stats,
            'totalEntities' => $totalEntities,
            'totalWithSeo' => $totalWithSeo,
            'totalAutoGenerated' => $totalAutoGenerated,
            'overallPercentage' => $overallPercentage,
            'recentActivity' => $recentActivity,
            'isConfigured' => $this->seoGenerator->isConfigured(),
            'languages' => SEOMetadata::LANGUAGES,
            'entityTypes' => SEOMetadata::ENTITY_TYPES,
            'flash' => $this->getFlash()
        ]);
    }

    /**
     * Mass generate SEO page
     */
    public function massGenerate(): void
    {
        $currentType = $_GET['type'] ?? 'page';
        $currentLanguage = $_GET['language'] ?? 'es';

        // Get entities without SEO for this type AND language
        $entitiesWithoutSeo = $this->seoModel->getEntitiesWithoutSEO($currentType, 100, $currentLanguage);

        $this->renderAdmin('seo/mass-generate', [
            'title' => 'Generación Masiva de SEO',
            'entitiesWithoutSeo' => $entitiesWithoutSeo,
            'currentType' => $currentType,
            'currentLanguage' => $currentLanguage,
            'entityTypes' => SEOMetadata::ENTITY_TYPES,
            'languages' => SEOMetadata::LANGUAGES,
            'isConfigured' => $this->seoGenerator->isConfigured(),
            'csrf_token' => $this->generateCsrf(),
            'flash' => $this->getFlash()
        ]);
    }

    /**
     * AJAX: Generate SEO for batch of entities
     */
    public function generateBatch(): void
    {
        header('Content-Type: application/json');

        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            echo json_encode(['success' => false, 'message' => 'Invalid request method']);
            exit;
        }

        $input = json_decode(file_get_contents('php://input'), true);

        $entityType = $input['entity_type'] ?? 'page';
        $language = $input['language'] ?? 'es';
        $offset = (int)($input['offset'] ?? 0);
        $batchSize = (int)($input['batch_size'] ?? 3);
        $overwrite = (bool)($input['overwrite'] ?? false);

        if (!$this->seoGenerator->isConfigured()) {
            echo json_encode(['success' => false, 'message' => 'OpenAI API key not configured']);
            exit;
        }

        try {
            $result = $this->seoGenerator->massGenerate(
                $entityType,
                $language,
                $offset,
                $batchSize,
                $overwrite
            );

            echo json_encode([
                'success' => true,
                'stats' => $result
            ]);
        } catch (\Exception $e) {
            echo json_encode([
                'success' => false,
                'message' => $e->getMessage()
            ]);
        }
        exit;
    }

    /**
     * AJAX: Generate SEO for single entity
     */
    public function generateSingle(): void
    {
        header('Content-Type: application/json');

        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            echo json_encode(['success' => false, 'message' => 'Invalid request method']);
            exit;
        }

        $input = json_decode(file_get_contents('php://input'), true);

        $entityType = $input['entity_type'] ?? '';
        $entityId = (int)($input['entity_id'] ?? 0);
        $language = $input['language'] ?? 'es';
        $overwrite = (bool)($input['overwrite'] ?? false);
        $allLanguages = (bool)($input['all_languages'] ?? false);

        if (!$entityType || !$entityId) {
            echo json_encode(['success' => false, 'message' => 'Entity type and ID are required']);
            exit;
        }

        if (!$this->seoGenerator->isConfigured()) {
            echo json_encode(['success' => false, 'message' => 'OpenAI API key not configured']);
            exit;
        }

        try {
            if ($allLanguages) {
                $result = $this->seoGenerator->generateForEntityAllLanguages($entityType, $entityId, $overwrite);
                $allSuccess = true;
                foreach ($result as $lang => $res) {
                    if (!$res['success']) {
                        $allSuccess = false;
                    }
                }
                echo json_encode([
                    'success' => $allSuccess,
                    'results' => $result,
                    'message' => $allSuccess ? 'SEO generated for all languages' : 'Some languages failed'
                ]);
            } else {
                $result = $this->seoGenerator->generateForEntity($entityType, $entityId, $language, $overwrite);
                echo json_encode($result);
            }
        } catch (\Exception $e) {
            echo json_encode([
                'success' => false,
                'message' => $e->getMessage()
            ]);
        }
        exit;
    }

    /**
     * View/Edit SEO for an entity
     */
    public function edit(): void
    {
        $entityType = $_GET['type'] ?? '';
        $entityId = (int)($_GET['id'] ?? 0);

        if (!$entityType || !$entityId) {
            $this->flash('error', 'Entity type and ID are required');
            $this->redirect('/admin/seo');
        }

        // Get entity content
        $entityContent = $this->seoModel->getEntityContent($entityType, $entityId);
        if (!$entityContent) {
            $this->flash('error', 'Entity not found');
            $this->redirect('/admin/seo');
        }

        // Get SEO for all languages
        $seoByLanguage = [];
        foreach (SEOMetadata::LANGUAGES as $langCode => $langName) {
            $seoByLanguage[$langCode] = $this->seoModel->getForEntity($entityType, $entityId, $langCode);
        }

        $this->renderAdmin('seo/edit', [
            'title' => 'Editar SEO',
            'entityType' => $entityType,
            'entityId' => $entityId,
            'entityContent' => $entityContent,
            'seoByLanguage' => $seoByLanguage,
            'languages' => SEOMetadata::LANGUAGES,
            'entityTypes' => SEOMetadata::ENTITY_TYPES,
            'isConfigured' => $this->seoGenerator->isConfigured(),
            'csrf_token' => $this->generateCsrf(),
            'flash' => $this->getFlash()
        ]);
    }

    /**
     * Save SEO metadata
     */
    public function save(): void
    {
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            $this->redirect('/admin/seo');
        }

        $this->validateCsrf();

        $entityType = $_POST['entity_type'] ?? '';
        $entityId = (int)($_POST['entity_id'] ?? 0);

        if (!$entityType || !$entityId) {
            $this->flash('error', 'Invalid request');
            $this->redirect('/admin/seo');
        }

        // Save SEO for each language
        foreach (SEOMetadata::LANGUAGES as $langCode => $langName) {
            $prefix = "seo_{$langCode}_";

            $seoData = [
                'meta_title' => $_POST[$prefix . 'meta_title'] ?? null,
                'meta_description' => $_POST[$prefix . 'meta_description'] ?? null,
                'og_title' => $_POST[$prefix . 'og_title'] ?? null,
                'og_description' => $_POST[$prefix . 'og_description'] ?? null,
                'og_image' => $_POST[$prefix . 'og_image'] ?? null,
                'canonical_url' => $_POST[$prefix . 'canonical_url'] ?? null,
                'robots' => $_POST[$prefix . 'robots'] ?? 'index, follow',
                'keywords' => $_POST[$prefix . 'keywords'] ?? null,
                'is_auto_generated' => 0 // Manual edit
            ];

            // Only save if at least one field has content
            $hasContent = !empty($seoData['meta_title']) || !empty($seoData['meta_description']);
            if ($hasContent) {
                $this->seoModel->saveForEntity($entityType, $entityId, $langCode, $seoData);
            }
        }

        $this->flash('success', 'SEO metadata saved successfully');
        $this->redirect("/admin/seo/edit?type={$entityType}&id={$entityId}");
    }

    /**
     * Sitemap management page
     */
    public function sitemap(): void
    {
        // Check if sitemap file exists
        $sitemapPath = __DIR__ . '/../../../public/sitemap.xml';
        $sitemapExists = file_exists($sitemapPath);
        $sitemapLastModified = $sitemapExists ? date('Y-m-d H:i:s', filemtime($sitemapPath)) : null;

        $this->renderAdmin('seo/sitemap', [
            'title' => 'Sitemap',
            'sitemapExists' => $sitemapExists,
            'sitemapLastModified' => $sitemapLastModified,
            'csrf_token' => $this->generateCsrf(),
            'flash' => $this->getFlash()
        ]);
    }

    /**
     * Generate and save sitemap
     */
    public function generateSitemap(): void
    {
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            $this->redirect('/admin/seo/sitemap');
        }

        $this->validateCsrf();

        try {
            $sitemapContent = SEOService::generateSitemap();
            $sitemapPath = __DIR__ . '/../../../public/sitemap.xml';

            if (file_put_contents($sitemapPath, $sitemapContent) !== false) {
                $this->flash('success', 'Sitemap generated successfully');
            } else {
                $this->flash('error', 'Failed to write sitemap file');
            }
        } catch (\Exception $e) {
            $this->flash('error', 'Error generating sitemap: ' . $e->getMessage());
        }

        $this->redirect('/admin/seo/sitemap');
    }

    /**
     * Robots.txt management page
     */
    public function robots(): void
    {
        $robotsPath = __DIR__ . '/../../../public/robots.txt';
        $robotsContent = file_exists($robotsPath) ? file_get_contents($robotsPath) : $this->seoGenerator->generateRobotsTxt();

        $this->renderAdmin('seo/robots', [
            'title' => 'Robots.txt',
            'robotsContent' => $robotsContent,
            'csrf_token' => $this->generateCsrf(),
            'flash' => $this->getFlash()
        ]);
    }

    /**
     * Save robots.txt
     */
    public function saveRobots(): void
    {
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            $this->redirect('/admin/seo/robots');
        }

        $this->validateCsrf();

        $content = $_POST['robots_content'] ?? '';

        // Save to file
        if ($this->seoGenerator->saveRobotsTxt($content)) {
            // Also save to settings for backup
            $this->settings->set('robots_txt_content', $content, 'textarea', 'seo');
            $this->flash('success', 'Robots.txt saved successfully');
        } else {
            $this->flash('error', 'Failed to save robots.txt file');
        }

        $this->redirect('/admin/seo/robots');
    }

    /**
     * SEO Settings page
     */
    public function settings(): void
    {
        $seoSettings = [
            'seo_auto_generate_on_publish' => $this->settings->get('seo_auto_generate_on_publish', '0'),
            'seo_default_robots' => $this->settings->get('seo_default_robots', 'index, follow'),
            'seo_title_suffix' => $this->settings->get('seo_title_suffix', ' | Omniwallet'),
            'seo_default_og_image' => $this->settings->get('seo_default_og_image', '/assets/images/og-default.jpg'),
        ];

        $this->renderAdmin('seo/settings', [
            'title' => 'SEO Settings',
            'seoSettings' => $seoSettings,
            'isConfigured' => $this->seoGenerator->isConfigured(),
            'csrf_token' => $this->generateCsrf(),
            'flash' => $this->getFlash()
        ]);
    }

    /**
     * Save SEO settings
     */
    public function saveSettings(): void
    {
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            $this->redirect('/admin/seo/settings');
        }

        $this->validateCsrf();

        $settings = [
            'seo_auto_generate_on_publish' => $_POST['seo_auto_generate_on_publish'] ?? '0',
            'seo_default_robots' => $_POST['seo_default_robots'] ?? 'index, follow',
            'seo_title_suffix' => $_POST['seo_title_suffix'] ?? '',
            'seo_default_og_image' => $_POST['seo_default_og_image'] ?? ''
        ];

        foreach ($settings as $key => $value) {
            $this->settings->set($key, $value, 'string', 'seo');
        }

        $this->flash('success', 'SEO settings saved successfully');
        $this->redirect('/admin/seo/settings');
    }

    /**
     * View audit log
     */
    public function auditLog(): void
    {
        $logs = $this->seoGenerator->getAuditLog(500);

        $this->renderAdmin('seo/audit-log', [
            'title' => 'SEO Audit Log',
            'logs' => $logs,
            'entityTypes' => SEOMetadata::ENTITY_TYPES,
            'flash' => $this->getFlash()
        ]);
    }

    /**
     * AJAX: Get SEO preview
     */
    public function preview(): void
    {
        header('Content-Type: application/json');

        $entityType = $_GET['type'] ?? '';
        $entityId = (int)($_GET['id'] ?? 0);
        $language = $_GET['language'] ?? 'es';

        $seo = $this->seoModel->getForEntity($entityType, $entityId, $language);

        echo json_encode([
            'success' => true,
            'seo' => $seo
        ]);
        exit;
    }
}
