<?php
/**
 * SEO Dashboard Template
 * Omniwallet CMS
 */
?>

<div class="page-header">
    <div class="page-header-content">
        <h1><i class="fas fa-search"></i> SEO Dashboard</h1>
        <p>Gestiona el SEO de todo el contenido</p>
    </div>
    <div class="page-header-actions">
        <?php if ($isConfigured): ?>
            <a href="/admin/seo/mass-generate" class="btn btn-primary">
                <i class="fas fa-magic"></i> Generación Masiva
            </a>
        <?php else: ?>
            <span class="badge badge-warning">
                <i class="fas fa-exclamation-triangle"></i> API no configurada
            </span>
        <?php endif; ?>
        <a href="/admin/seo/sitemap" class="btn btn-outline">
            <i class="fas fa-sitemap"></i> Sitemap
        </a>
        <a href="/admin/seo/robots" class="btn btn-outline">
            <i class="fas fa-robot"></i> Robots.txt
        </a>
        <a href="/admin/seo/settings" class="btn btn-outline">
            <i class="fas fa-cog"></i> Configuración
        </a>
    </div>
</div>

<?php if ($flash): ?>
    <div class="alert alert-<?= $flash['type'] ?>">
        <?= $flash['message'] ?>
    </div>
<?php endif; ?>

<!-- Overall Statistics -->
<div class="stats-grid seo-overview-stats">
    <div class="stat-card stat-card-primary">
        <div class="stat-icon"><i class="fas fa-file-alt"></i></div>
        <span class="stat-value"><?= $totalEntities ?></span>
        <span class="stat-label">Total Contenidos</span>
    </div>
    <div class="stat-card stat-card-success">
        <div class="stat-icon"><i class="fas fa-check-circle"></i></div>
        <span class="stat-value"><?= $totalWithSeo ?></span>
        <span class="stat-label">Con SEO</span>
    </div>
    <div class="stat-card stat-card-warning">
        <div class="stat-icon"><i class="fas fa-exclamation-triangle"></i></div>
        <span class="stat-value"><?= $totalEntities - $totalWithSeo ?></span>
        <span class="stat-label">Sin SEO</span>
    </div>
    <div class="stat-card stat-card-info">
        <div class="stat-icon"><i class="fas fa-robot"></i></div>
        <span class="stat-value"><?= $totalAutoGenerated ?></span>
        <span class="stat-label">Auto-generados</span>
    </div>
</div>

<!-- Overall Progress -->
<div class="card seo-progress-card">
    <div class="card-header">
        <h3><i class="fas fa-chart-line"></i> Cobertura SEO General</h3>
        <span class="badge badge-<?= $overallPercentage >= 80 ? 'success' : ($overallPercentage >= 50 ? 'warning' : 'danger') ?>">
            <?= $overallPercentage ?>%
        </span>
    </div>
    <div class="card-body">
        <div class="progress-bar-large">
            <div class="progress-fill" style="width: <?= $overallPercentage ?>%"></div>
        </div>
        <p class="progress-text">
            <?= $totalWithSeo ?> de <?= $totalEntities ?> contenidos tienen metadatos SEO
        </p>
    </div>
</div>

<!-- Stats by Content Type -->
<div class="card">
    <div class="card-header">
        <h3><i class="fas fa-th-list"></i> SEO por Tipo de Contenido</h3>
    </div>
    <div class="card-body">
        <div class="seo-types-grid">
            <?php foreach ($stats as $type => $stat): ?>
                <div class="seo-type-card">
                    <div class="seo-type-header">
                        <h4><?= htmlspecialchars($stat['label']) ?></h4>
                        <span class="badge badge-<?= $stat['percentage'] >= 80 ? 'success' : ($stat['percentage'] >= 50 ? 'warning' : 'danger') ?>">
                            <?= $stat['percentage'] ?>%
                        </span>
                    </div>
                    <div class="seo-type-progress">
                        <div class="progress-bar-small">
                            <div class="progress-fill" style="width: <?= $stat['percentage'] ?>%"></div>
                        </div>
                    </div>
                    <div class="seo-type-stats">
                        <span><i class="fas fa-check text-success"></i> <?= $stat['with_seo'] ?> con SEO</span>
                        <span><i class="fas fa-times text-danger"></i> <?= $stat['without_seo'] ?> sin SEO</span>
                        <span><i class="fas fa-robot text-info"></i> <?= $stat['auto_generated'] ?> auto</span>
                    </div>
                    <div class="seo-type-actions">
                        <a href="/admin/seo/mass-generate?type=<?= $type ?>" class="btn btn-sm btn-outline">
                            <i class="fas fa-magic"></i> Generar
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<!-- Quick Links -->
<div class="card">
    <div class="card-header">
        <h3><i class="fas fa-tools"></i> Herramientas SEO</h3>
    </div>
    <div class="card-body">
        <div class="quick-links-grid">
            <a href="/admin/seo/sitemap" class="quick-link-card">
                <i class="fas fa-sitemap"></i>
                <h4>Sitemap XML</h4>
                <p>Generar y gestionar el sitemap</p>
            </a>
            <a href="/admin/seo/robots" class="quick-link-card">
                <i class="fas fa-robot"></i>
                <h4>Robots.txt</h4>
                <p>Configurar directivas de rastreo</p>
            </a>
            <a href="/admin/seo/audit-log" class="quick-link-card">
                <i class="fas fa-history"></i>
                <h4>Historial</h4>
                <p>Ver log de cambios SEO</p>
            </a>
            <a href="/admin/seo/settings" class="quick-link-card">
                <i class="fas fa-cog"></i>
                <h4>Configuración</h4>
                <p>Ajustes generales de SEO</p>
            </a>
        </div>
    </div>
</div>

<!-- Recent Activity -->
<?php if (!empty($recentActivity)): ?>
<div class="card">
    <div class="card-header">
        <h3><i class="fas fa-clock"></i> Actividad Reciente</h3>
        <a href="/admin/seo/audit-log" class="btn btn-sm btn-outline">Ver todo</a>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Acción</th>
                    <th>Tipo</th>
                    <th>ID</th>
                    <th>Usuario</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($recentActivity as $log): ?>
                    <tr>
                        <td><?= date('d/m/Y H:i', strtotime($log['created_at'])) ?></td>
                        <td>
                            <span class="badge badge-<?= $log['action'] === 'generate' ? 'success' : ($log['action'] === 'update' ? 'info' : 'warning') ?>">
                                <?= ucfirst($log['action']) ?>
                            </span>
                        </td>
                        <td><?= $entityTypes[$log['entity_type']] ?? $log['entity_type'] ?></td>
                        <td>#<?= $log['entity_id'] ?></td>
                        <td><?= htmlspecialchars($log['user_name'] ?? 'Sistema') ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php endif; ?>

<style>
.seo-overview-stats {
    grid-template-columns: repeat(4, 1fr);
}

.seo-progress-card .progress-bar-large {
    height: 24px;
    background: var(--color-gray-200);
    border-radius: var(--radius-md);
    overflow: hidden;
}

.progress-bar-large .progress-fill,
.progress-bar-small .progress-fill {
    height: 100%;
    background: linear-gradient(90deg, var(--color-primary) 0%, var(--color-primary-dark) 100%);
    border-radius: var(--radius-md);
    transition: width 0.3s ease;
}

.progress-text {
    margin-top: var(--spacing-sm);
    color: var(--color-gray-600);
    text-align: center;
}

.seo-types-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: var(--spacing-lg);
}

.seo-type-card {
    background: var(--color-gray-50);
    border-radius: var(--radius-md);
    padding: var(--spacing-lg);
}

.seo-type-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: var(--spacing-md);
}

.seo-type-header h4 {
    margin: 0;
    font-size: 14px;
}

.seo-type-progress {
    margin-bottom: var(--spacing-md);
}

.progress-bar-small {
    height: 8px;
    background: var(--color-gray-200);
    border-radius: var(--radius-sm);
    overflow: hidden;
}

.seo-type-stats {
    display: flex;
    flex-wrap: wrap;
    gap: var(--spacing-sm);
    font-size: 13px;
    color: var(--color-gray-600);
    margin-bottom: var(--spacing-md);
}

.seo-type-stats span {
    display: flex;
    align-items: center;
    gap: 4px;
}

.quick-links-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    gap: var(--spacing-lg);
}

.quick-link-card {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: var(--spacing-xl);
    background: var(--color-gray-50);
    border-radius: var(--radius-md);
    text-align: center;
    text-decoration: none;
    color: var(--color-gray-700);
    transition: all 0.2s ease;
}

.quick-link-card:hover {
    background: var(--color-primary);
    color: white;
    transform: translateY(-2px);
}

.quick-link-card i {
    font-size: 2rem;
    margin-bottom: var(--spacing-md);
    color: var(--color-primary);
    transition: color 0.2s ease;
}

.quick-link-card:hover i {
    color: white !important;
}

.quick-link-card:hover h4,
.quick-link-card:hover p {
    color: white;
}

.quick-link-card h4 {
    margin: 0 0 var(--spacing-xs) 0;
}

.quick-link-card p {
    margin: 0;
    font-size: var(--font-size-sm);
    opacity: 0.8;
}

@media (max-width: 768px) {
    .seo-overview-stats {
        grid-template-columns: repeat(2, 1fr);
    }
}
</style>
