<?php
/**
 * SEO Metadata Model
 * Manages SEO metadata for all content types with multi-language support
 * Omniwallet CMS
 */

namespace App\Models;

use App\Core\Model;

class SEOMetadata extends Model
{
    protected string $table = 'seo_metadata';

    protected array $fillable = [
        'entity_type',
        'entity_id',
        'language',
        'meta_title',
        'meta_description',
        'og_title',
        'og_description',
        'og_image',
        'canonical_url',
        'robots',
        'keywords',
        'schema_type',
        'schema_data',
        'is_auto_generated',
        'generation_source',
        'generated_at'
    ];

    /**
     * Supported entity types
     */
    public const ENTITY_TYPES = [
        'page' => 'Páginas',
        'post' => 'Blog Posts',
        'success_case' => 'Casos de Éxito',
        'service' => 'Servicios',
        'tool' => 'Herramientas',
        'client' => 'Clientes',
        'landing' => 'Landings',
        'category' => 'Categorías'
    ];

    /**
     * Supported languages
     */
    public const LANGUAGES = [
        'es' => 'Español',
        'en' => 'English',
        'it' => 'Italiano',
        'fr' => 'Français',
        'de' => 'Deutsch'
    ];

    /**
     * Get SEO metadata for an entity
     */
    public function getForEntity(string $entityType, int $entityId, string $language = 'es'): ?array
    {
        return $this->first([
            'entity_type' => $entityType,
            'entity_id' => $entityId,
            'language' => $language
        ]);
    }

    /**
     * Get all SEO metadata for an entity (all languages)
     */
    public function getAllForEntity(string $entityType, int $entityId): array
    {
        return $this->where([
            'entity_type' => $entityType,
            'entity_id' => $entityId
        ], ['language' => 'ASC']);
    }

    /**
     * Save or update SEO metadata
     */
    public function saveForEntity(string $entityType, int $entityId, string $language, array $data): int
    {
        $existing = $this->getForEntity($entityType, $entityId, $language);

        $data['entity_type'] = $entityType;
        $data['entity_id'] = $entityId;
        $data['language'] = $language;

        if ($existing) {
            $this->update($existing['id'], $data);
            return $existing['id'];
        } else {
            return $this->create($data);
        }
    }

    /**
     * Delete SEO metadata for an entity
     */
    public function deleteForEntity(string $entityType, int $entityId, ?string $language = null): bool
    {
        $sql = "DELETE FROM {$this->table} WHERE entity_type = ? AND entity_id = ?";
        $params = [$entityType, $entityId];

        if ($language) {
            $sql .= " AND language = ?";
            $params[] = $language;
        }

        $stmt = $this->db->query($sql, $params);
        return $stmt->rowCount() > 0;
    }

    /**
     * Get SEO statistics
     */
    public function getStats(): array
    {
        $db = $this->db->getConnection();
        $stats = [];

        foreach (self::ENTITY_TYPES as $type => $label) {
            // Get total entities of this type
            $totalQuery = $this->getEntityCountQuery($type);
            if ($totalQuery) {
                $stmt = $db->query($totalQuery);
                $total = (int)$stmt->fetchColumn();
            } else {
                $total = 0;
            }

            // Get entities with SEO (at least Spanish)
            $stmt = $db->prepare("
                SELECT COUNT(DISTINCT entity_id)
                FROM {$this->table}
                WHERE entity_type = ? AND language = 'es'
                AND (meta_title IS NOT NULL AND meta_title != '')
            ");
            $stmt->execute([$type]);
            $withSeo = (int)$stmt->fetchColumn();

            // Get auto-generated count
            $stmt = $db->prepare("
                SELECT COUNT(DISTINCT entity_id)
                FROM {$this->table}
                WHERE entity_type = ? AND is_auto_generated = 1
            ");
            $stmt->execute([$type]);
            $autoGenerated = (int)$stmt->fetchColumn();

            $stats[$type] = [
                'label' => $label,
                'total' => $total,
                'with_seo' => $withSeo,
                'without_seo' => max(0, $total - $withSeo),
                'auto_generated' => $autoGenerated,
                'percentage' => $total > 0 ? round(($withSeo / $total) * 100) : 0
            ];
        }

        return $stats;
    }

    /**
     * Get query to count entities of a given type
     */
    private function getEntityCountQuery(string $type): ?string
    {
        $queries = [
            'page' => "SELECT COUNT(*) FROM pages WHERE status = 'published'",
            'post' => "SELECT COUNT(*) FROM posts WHERE status = 'published'",
            'success_case' => "SELECT COUNT(*) FROM success_cases WHERE status = 'published'",
            'service' => "SELECT COUNT(*) FROM services WHERE is_active = 1",
            'tool' => "SELECT COUNT(*) FROM tools WHERE is_active = 1",
            'client' => "SELECT COUNT(*) FROM clients WHERE is_active = 1",
            'landing' => "SELECT COUNT(*) FROM landings WHERE is_active = 1",
            'category' => "SELECT COUNT(*) FROM categories WHERE is_active = 1"
        ];

        return $queries[$type] ?? null;
    }

    /**
     * Get entities without SEO metadata for a specific language
     */
    public function getEntitiesWithoutSEO(string $entityType, int $limit = 50, string $language = 'es'): array
    {
        $db = $this->db->getConnection();

        $tableConfig = $this->getEntityTableConfig($entityType);
        if (!$tableConfig) {
            return [];
        }

        $sql = "
            SELECT e.id, e.{$tableConfig['title_field']} as title, e.slug
            FROM {$tableConfig['table']} e
            LEFT JOIN {$this->table} s ON s.entity_type = ? AND s.entity_id = e.id AND s.language = ?
            WHERE {$tableConfig['active_condition']}
            AND (s.id IS NULL OR s.meta_title IS NULL OR s.meta_title = '')
            ORDER BY e.id DESC
            LIMIT ?
        ";

        $stmt = $db->prepare($sql);
        $stmt->execute([$entityType, $language, $limit]);

        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }

    /**
     * Get table configuration for each entity type
     */
    private function getEntityTableConfig(string $type): ?array
    {
        $configs = [
            'page' => [
                'table' => 'pages',
                'title_field' => 'title',
                'content_field' => 'content',
                'active_condition' => "status = 'published'"
            ],
            'post' => [
                'table' => 'posts',
                'title_field' => 'title',
                'content_field' => 'content',
                'active_condition' => "status = 'published'"
            ],
            'success_case' => [
                'table' => 'success_cases',
                'title_field' => 'title',
                'content_field' => 'challenge',
                'active_condition' => "status = 'published'"
            ],
            'service' => [
                'table' => 'services',
                'title_field' => 'title',
                'content_field' => 'full_description',
                'active_condition' => "is_active = 1"
            ],
            'tool' => [
                'table' => 'tools',
                'title_field' => 'title',
                'content_field' => 'description',
                'active_condition' => "is_active = 1"
            ],
            'client' => [
                'table' => 'clients',
                'title_field' => 'name',
                'content_field' => 'description',
                'active_condition' => "is_active = 1"
            ],
            'landing' => [
                'table' => 'landings',
                'title_field' => 'title',
                'content_field' => 'description',
                'active_condition' => "is_active = 1"
            ],
            'category' => [
                'table' => 'categories',
                'title_field' => 'name',
                'content_field' => 'description',
                'active_condition' => "is_active = 1"
            ]
        ];

        return $configs[$type] ?? null;
    }

    /**
     * Get entity content for SEO generation
     */
    public function getEntityContent(string $entityType, int $entityId): ?array
    {
        $db = $this->db->getConnection();
        $config = $this->getEntityTableConfig($entityType);

        if (!$config) {
            return null;
        }

        $stmt = $db->prepare("SELECT * FROM {$config['table']} WHERE id = ?");
        $stmt->execute([$entityId]);

        return $stmt->fetch(\PDO::FETCH_ASSOC) ?: null;
    }

    /**
     * Log SEO audit action
     */
    public function logAudit(
        ?int $seoMetadataId,
        string $entityType,
        int $entityId,
        string $action,
        ?string $fieldChanged = null,
        ?string $oldValue = null,
        ?string $newValue = null,
        ?int $userId = null
    ): void {
        try {
            $sql = "INSERT INTO seo_audit_log
                    (seo_metadata_id, entity_type, entity_id, action, field_changed, old_value, new_value, performed_by)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

            $this->db->query($sql, [
                $seoMetadataId,
                $entityType,
                $entityId,
                $action,
                $fieldChanged,
                $oldValue,
                $newValue,
                $userId
            ]);
        } catch (\Exception $e) {
            // Log error but don't fail the main operation
            error_log("SEO Audit Log Error: " . $e->getMessage());
        }
    }
}
